In [1]:
from keras.models import load_model

In [2]:
import pandas as pd
import numpy as np

In [3]:
import os
print(os.getcwd())
os.chdir(r'd:\\vscode_machineLearning\\internship\\sentiment-Analysis-fellowship.ai')

d:\vscode_machineLearning\internship\sentiment-Analysis-fellowship.ai\notebooks


In [4]:
model = load_model(r'sentimentAnalysisModel')

In [5]:
model.summary()

Model: "LSTM_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_layer (Embedding)     (None, 150, 100)          5694200   
                                                                 
 LSTM_1 (Bidirectional)      (None, 150, 128)          84480     
                                                                 
 dropout_2 (Dropout)         (None, 150, 128)          0         
                                                                 
 batch_normalization_1 (Bat  (None, 150, 128)          512       
 chNormalization)                                                
                                                                 
 dropout_3 (Dropout)         (None, 150, 128)          0         
                                                                 
 LSTM_2 (Bidirectional)      (None, 64)                41216     
                                                        

## testing

In [6]:
padded_docs = pd.read_csv(r'sentiment-analysis-dataset\padded_docs.csv')
padded_docs = padded_docs.drop(columns='Unnamed: 0')

In [7]:
padded_docs = padded_docs.iloc[:,:150]

In [8]:
padded_docs=np.array(padded_docs)
padded_docs = np.array(padded_docs)

In [9]:
padded_docs[[0]]

array([[    3,   237,   317,     8,  3680,   216,   440,   131,    24,
           32,  2294,  3680,   996,  9208,    19,    88,   134,   332,
         1209,    21,  4362,   442,    21,   452,  1695,   937,   338,
          263,    56,   130,  3680,  5646,   232, 10499,  4639,  1581,
          534,   905,  1097, 13548,  2967,  1882,   802,  1939,  1845,
          744,   251, 12671,   223,  6462,   517,   312,  1824,   300,
         4908,   346,  5480,  7134,    38,   126,    10,    41,   157,
          756,    21,   490,   122,   165,    21,   582,    80,   324,
          972,  2025,   582,   582,   845,    24,   216,    51,    99,
         2294,  1310,    41,  1207,     8,   373,  1049,    83,  6109,
          223,   568,  1103,  4950,  1721,  2152,  4077,    91,   414,
            6,   188,    44,   571,   676,  4077,    77,   802,  4419,
          490,   224,   685,   998,   802,     8,    87,    97,  1609,
         2375,     6,   423,  2947,     0,     0,     0,     0,     0,
      

In [36]:
model.predict(padded_docs[[7865]])

1/1 [==============================] - 0s 55ms/step


array([[0.998613]], dtype=float32)

## testing with encoding

In [13]:
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

In [32]:
def preprocess_input(text:str):
    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(texts=text)
    docs = tokenizer.texts_to_sequences(text)
    pad_docs = pad_sequences(sequences=docs,maxlen=150,padding='post')
    return np.array(pad_docs)

In [33]:
text = preprocess_input(text='12,im big fan work many enjoyed movie postal im boll apparently bought rights use far cry long ago even game even people enjoyed killing mercs infiltrating secret research labs located tropical island far something mr boll schemed together along legion feeling loneley set mr boll invites three countrymen play players go names til udo kier ralf names actually made selfs pretty big movie tale goes like jack carver played til schweiger carver german hail bratwurst eating however find tils acting movie pretty people complained really staying true whole carver agenda saw carver first person perspective really know looked like kicking storyline film beyond see evil mad scientist krieger played udo making gms performing research island reminds vancouver thats right palm trees instead got nice rich even gone far started cry cannot go wanna stay true bolls shenanigans go see movie disappointed delivers true boll meaning things worth mentioning would imply boll good work areas film nice boat fighting whole gms squad enters scene everything makes movie far cry reeks scheisse poop wanna take wiff go btw carver gets annoying sidekick makes wanna shoot first three minutes,0')

In [34]:
pred = model.predict(text)

37/37 [==============================] - 2s 42ms/step


In [35]:
pred

array([[0.11051664],
       [0.15846196],
       [0.05775732],
       ...,
       [0.05100874],
       [0.05775733],
       [0.06046253]], dtype=float32)

In [29]:
max(pred)

array([0.15846196], dtype=float32)