In [1]:
from keras.models import load_model

In [2]:
import pandas as pd
import numpy as np

In [3]:
import os
print(os.getcwd())
os.chdir(r'd:\\vscode_machineLearning\\internship\\sentiment-Analysis-fellowship.ai')

d:\vscode_machineLearning\internship\sentiment-Analysis-fellowship.ai\notebooks


In [4]:
model = load_model(r'sentimentAnalysisModel')

In [5]:
model.summary()

Model: "LSTM_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_layer (Embedding)     (None, 150, 100)          5694200   
                                                                 
 LSTM_1 (Bidirectional)      (None, 150, 128)          84480     
                                                                 
 dropout_2 (Dropout)         (None, 150, 128)          0         
                                                                 
 batch_normalization_1 (Bat  (None, 150, 128)          512       
 chNormalization)                                                
                                                                 
 dropout_3 (Dropout)         (None, 150, 128)          0         
                                                                 
 LSTM_2 (Bidirectional)      (None, 64)                41216     
                                                        

## testing

In [6]:
padded_docs = pd.read_csv(r'sentiment-analysis-dataset\padded_docs.csv')
padded_docs = padded_docs.drop(columns='Unnamed: 0')

In [7]:
padded_docs = padded_docs.iloc[:,:150]

In [8]:
padded_docs=np.array(padded_docs)
padded_docs = np.array(padded_docs)

In [9]:
type(padded_docs[[0]])

numpy.ndarray

In [10]:
padded_docs[[0]]

array([[    3,   237,   317,     8,  3680,   216,   440,   131,    24,
           32,  2294,  3680,   996,  9208,    19,    88,   134,   332,
         1209,    21,  4362,   442,    21,   452,  1695,   937,   338,
          263,    56,   130,  3680,  5646,   232, 10499,  4639,  1581,
          534,   905,  1097, 13548,  2967,  1882,   802,  1939,  1845,
          744,   251, 12671,   223,  6462,   517,   312,  1824,   300,
         4908,   346,  5480,  7134,    38,   126,    10,    41,   157,
          756,    21,   490,   122,   165,    21,   582,    80,   324,
          972,  2025,   582,   582,   845,    24,   216,    51,    99,
         2294,  1310,    41,  1207,     8,   373,  1049,    83,  6109,
          223,   568,  1103,  4950,  1721,  2152,  4077,    91,   414,
            6,   188,    44,   571,   676,  4077,    77,   802,  4419,
          490,   224,   685,   998,   802,     8,    87,    97,  1609,
         2375,     6,   423,  2947,     0,     0,     0,     0,     0,
      

In [12]:
model.predict(padded_docs[[7865]])

1/1 [==============================] - 2s 2s/step


array([[0.998613]], dtype=float32)

## testing with encoding

In [16]:
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from bs4 import BeautifulSoup
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [18]:
class preprocess_input:
    def __init__(self, text):
        self.text = text.lower()  # Initialize the text attribute
    
    # remove html tags
    def remove_html_tags(self):
        soup = BeautifulSoup(self.text, "html.parser")
        return soup.get_text()
    
    def remove_between_square_brackets(self):
        return re.sub(r'http\S+', '', self.text)
    
    def remove_stopwords(self):
        stop = set(stopwords.words('english'))
        final_text = []
        for i in self.text.split():
            if i.strip().lower() not in stop and i.strip().lower().isalpha():
                final_text.append(i.strip().lower())
        return " ".join(final_text)
    
    def use_all(self):
        txt = self.remove_html_tags()
        txt = self.remove_between_square_brackets()
        txt = self.remove_stopwords()
        return txt
    
    def __str__(self) -> str:
        return self.use_all()
    

txt = """ im big fan work many enjoyed movie postal im boll apparently bought rights use far cry long ago even game even
 people enjoyed killing mercs infiltrating secret research labs located tropical island far something mr boll schemed together
   along legion feeling loneley set mr boll invites three countrymen play players go names til udo kier ralf names actually made 
   selfs pretty big movie tale goes like jack carver played til schweiger carver german hail bratwurst eating however find tils acting movie pretty
     people complained really staying true whole carver agenda saw carver first person perspective really know looked like kicking storyline film beyond 
     see evil mad scientist krieger played udo making gms performing research island reminds vancouver thats right palm trees instead got nice rich even gone 
     far started cry cannot go wanna stay true bolls shenanigans go see movie disappointed delivers true boll meaning things worth mentioning would imply boll
       good work areas film nice boat fighting whole gms squad enters scene everything makes movie far cry reeks scheisse poop wanna take wiff go btw carver gets
         annoying sidekick makes wanna shoot first three minutes"""

obj = preprocess_input(text=txt)
print(obj)


im big fan work many enjoyed movie postal im boll apparently bought rights use far cry long ago even game even people enjoyed killing mercs infiltrating secret research labs located tropical island far something mr boll schemed together along legion feeling loneley set mr boll invites three countrymen play players go names til udo kier ralf names actually made selfs pretty big movie tale goes like jack carver played til schweiger carver german hail bratwurst eating however find tils acting movie pretty people complained really staying true whole carver agenda saw carver first person perspective really know looked like kicking storyline film beyond see evil mad scientist krieger played udo making gms performing research island reminds vancouver thats right palm trees instead got nice rich even gone far started cry cannot go wanna stay true bolls shenanigans go see movie disappointed delivers true boll meaning things worth mentioning would imply boll good work areas film nice boat fighti

In [ ]:
ps = PorterStemmer()
corpus = []
for i in tqdm(range(0,len(X)),desc ="build corpus"):
    stemmed_words = [ps.stem(word) for word in X[i].split()]
    text = ' '.join(stemmed_words)
    corpus.append(text)
    
    # print(' '.join(stemmed_words))
corpus

In [15]:
def tokenize_vectorize_input(text:str):
    ps = PorterStemmer()

    stemmed_words = [ps.stem(word) for word in text.split()]
    tokenizer = Tokenizer()
    print(tokenizer)
    tokenizer.fit_on_texts(texts=text)
    print(tokenizer)
    docs = tokenizer.texts_to_sequences(text)
    print(docs)
    pad_docs = pad_sequences(sequences=docs,maxlen=150,padding='post')
    print(pad_docs)
    return np.array(pad_docs)

tokenize_vectorize_input(obj.text)


[[3], [11], [], [21], [3], [10], [], [19], [2], [4], [], [20], [6], [5], [18], [], [11], [2], [4], [14], [], [1], [4], [23], [6], [14], [1], [13], [], [11], [6], [17], [3], [1], [], [15], [6], [8], [7], [2], [9], [], [3], [11], [], [21], [6], [9], [9], [], [2], [15], [15], [2], [5], [1], [4], [7], [9], [14], [], [21], [6], [22], [10], [16], [7], [], [5], [3], [10], [16], [7], [8], [], [22], [8], [1], [], [19], [2], [5], [], [12], [5], [14], [], [9], [6], [4], [10], [], [2], [10], [6], [], [1], [17], [1], [4], [], [10], [2], [11], [1], [], [1], [17], [1], [4], [], [15], [1], [6], [15], [9], [1], [], [1], [4], [23], [6], [14], [1], [13], [], [18], [3], [9], [9], [3], [4], [10], [], [11], [1], [5], [12], [8], [], [3], [4], [19], [3], [9], [7], [5], [2], [7], [3], [4], [10], [], [8], [1], [12], [5], [1], [7], [], [5], [1], [8], [1], [2], [5], [12], [16], [], [9], [2], [21], [8], [], [9], [6], [12], [2], [7], [1], [13], [], [7], [5], [6], [15], [3], [12], [2], [9], [], [3], [8], [9], [2], [

array([[ 3,  0,  0, ...,  0,  0,  0],
       [11,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 7,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       [ 8,  0,  0, ...,  0,  0,  0]])

In [ ]:
text[3]

array([21,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [ ]:
pred = model.predict(text)

37/37 [==============================] - 3s 43ms/step


In [ ]:
pred

array([[0.11051664],
       [0.15846196],
       [0.05775732],
       ...,
       [0.05100874],
       [0.05775733],
       [0.06046253]], dtype=float32)

In [ ]:
max(pred)

array([0.15846196], dtype=float32)